version: '3'
services:
  mariadb:
    image: mariadb
    restart: unless-stopped
    environment:
    - MYSQL_ROOT_PASSWORD=${MARIADB_PASSWORD}
    - MYSQL_DATABASE=unichannel
    ports:
    - 127.0.0.1:3306:3306
    volumes:
    - './unichannel/database:/var/lib/mysql'
  uwsgi:
    build: .
    user: "${UID}:${GID}"
    restart: unless-stopped
    environment:
    - MARIADB_PASSWORD
    - SENTRY_DSN
    volumes:
    - ./unichannel/firebase.json:/firebase.json
    - ./unichannel/media:/media
    - ./unichannel/logs:/logs
    depends_on:
    - mariadb
  task_processor:
    build: .
    restart: unless-stopped
    user: "${UID}:${GID}"
    environment:
    - MARIADB_PASSWORD
    - SENTRY_DSN=${TASK_SENTRY_DNS}
    volumes:
    - ./unichannel/firebase.json:/firebase.json
    - ./unichannel/media:/media
    depends_on:
    - mariadb
    command: python manage.py process_tasks
  nginx:
    build: app/.
    restart: unless-stopped
    ports:
    - 127.0.0.1:8000:80
    - 80:80
    volumes:
    - ./unichannel/media:/static/media
    depends_on:
    - uwsgi
