version: '3'
services:
  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIA_PASS}
      MYSQL_DATABASE: uknow
    ports:
    - 127.0.0.1:3306:3306
    volumes:
    - './unichannel/database:/var/lib/mysql'
  uwsgi:
    build: .
    user: "${UID}:${GID}"
    environment:
    - MARIA_PASS
    - SENTRY_DSN
    volumes:
    - ./unichannel/firebase.json:/firebase.json
    - ./unichannel/media:/media
    - ./unichannel/logs:/logs
    depends_on:
    - mariadb
  task_processor:
    build: .
    user: "${UID}:${GID}"
    environment:
    - MARIA_PASS
    - SENTRY_DSN
    volumes:
    - ./unichannel/firebase.json:/firebase.json
    - ./unichannel/media:/media
    depends_on:
    - mariadb
    command: python manage.py process_tasks
  nginx:
    build: app/.
    ports:
    - 127.0.0.1:8000:80
    - 80:80
    volumes:
    - ./unichannel/media:/static/media
    depends_on:
    - uwsgi